"""
BIGAI ENGINE AI DL ARCHITECTURES
"""
from ENGINE.AI.DL.ARCHITECTURES import DARNN
from ENGINE.AI.DL.ARCHITECTURES import TFT
from ENGINE.AI.DL.ARCHITECTURES.MLP_PYTORCH import MLP_PYTORCH_LIGHNING
from ENGINE.AI.DL.ARCHITECTURES.MLP_PYTORCH import MLP_PYTORCH



__all__ = ["DARNN", "TFT","MLP_PYTORCH_LIGHNING","MLP_PYTORCH"]

__version__ = "0.0.6"